### ISSUE TITLE
Support for A4 signature_paper

### ISSUE THREAD

**Issue by IntLucas** [harrellbm/Bookletic#1]
Any chance to get support for A4 paper format?

**Comment by harrellbm** [comment]
I will definitely look into this. Right now the page sizes are hardcoded so would like to find a way to make it possible to use types built in page sizing. Hopefully I'll have some time to get this added soon!

**Comment by IntLucas** [comment]
Sounds great, looking forward to it!

**Comment by harrellbm** [comment]
#2 closed this request and allows you to use the regular page function to define the paper you are using! This should be a huge improvement in flexibility!
